dist: xenial
language: python
python:
 - "3.6"
env:
 -DJANGO=2.2.1
install:
 - pip install -r requirements.txt
before_script:
 - mysql -e 'create database test;' -u root
script:
 - python manage.py test
