dist: xenial
language: python
python:
 - "3.6"
services: postgresql
env:
 -DJANGO=2.2.1
install:
 - pip install -r requirements.txt
 - pip install psycopg2 --quiet
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
 - python manage.py test
