dist: xenial
language: python
python:
 - "3.6"
services:
 - mysql
env:
 -DJANGO=2.2.1
install:
 - pip install -r requirements.txt
 - pip install psycopg2 --quiet
before_script:
  - mysql -e 'create database test;' -u root
script:
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test
